### PR TITLE
Use HTML5 Required Attribute

### PR DESCRIPTION
**Pull request by srsgores**
This will allow forms to use the native HTML5 `required` attribute.  Tested, and working on my end.

### CODE REVIEW

**Comment by piotrekbator** [comment]
@srsgores There are two problems with this PR:

1. It doesn't work (see failing tests).
2. This probably shouldn't be the default behavior. Setting `required` attribute on inputs triggers an ugly native popover when users fail to fill those inputs. This both duplicates your own validation error messages and negatively impacts the UI.

It might be reasonable to implement this feature but hide it behind a configuration option so that user's would opt-in for it. But I think that the simples solution would be to do it by yourself in the app itself - just [copy the template](https://github.com/DockYard/ember-validations) and customize it there.

**Comment by srsgores** [comment]
I'll check the tests, but with another pull request I have coming which actually only displays error messages on focus out, I don't think there will be an issue.  At the very least, I think we should allow an option to try to comply with the spec.

**Comment by piotrekbator** [comment]
I'm sorry, but I think I need you to break this into separate PRs :|

First, because you reverted a commit that has nothing to do with subsequent changes and - as far as I'm concerned - it cannot be reverted.

Second, you seem to be implementing some changes in how configuration is loaded, but haven't provided any explanation as to why this changes are needed and what are you trying to achieve.

Third: changes you implemented in errors markup will break how the library works for people already using it. I agree this approach is semantically better, but I think we need to make it backwards compatible by default, or think of some way to show deprecation messages to people before switching to this markup as default.

And lastly - there seem to be multiple syntax and styling errors - at least according to Travis.

So, let's start with resolving the issue you tried fixing by reverting my commit - I've already asked for details in the comment to my commit. I'm happy to fix it myself, when I'll be able to reproduce it.

Then, let's first discuss the changes you wish to make, before implementing them. And let's make one PR per feature. OK?

**Comment by srsgores** [comment]
I thought this PR was closed while I worked on things.  I agree that this needs more work.

**Pull request closed without merging**
